---
abstract: 'humane syntax for matching files and directories'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Rules
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: 0
  Path::Class: 0
  Test::More: 0
  perl: 5.008003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-Rules
  homepage: http://perl.peknet.com/wiki/FileRules
  license: http://dev.perl.org/licenses/
  repository: http://svn.peknet.com/perl/File-Rules
version: 0.02
